##
## SPRING BOOT SETTINGS
##

server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

##
## DATABASE SETTINGS
##

database:
  # what CRS persisted geometries do have
  srid: EPSG:4326
  jpa:
    persistence-location: "classpath:META-INF/persistence.xml"

spring:
  datasource:
    username: postrges
    password: postrges
    url: jdbc:postgresql://localhost:5432/proxy
    #url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    #data: classpath:/META-INF/data-${spring.datasource.platform}.sql
    initialization-mode: always
  jpa:
    properties:
      hibernate: 
        hbm2ddl:
          # hbm2ddl values: validate | update | create | create-drop
          auto: create-drop
        jdbc:
          time_zone: UTC
          # https://hibernate.atlassian.net/browse/HHH-12368
          lob.non_contextual_creation: true
        format_sql: true
        default_schema: public
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

        # disable driver's feature detection
        # see https://stackoverflow.com/questions/46493500/hibernate-with-c3p0-createclob-is-not-yet-implemented
        temp.use_jdbc_metadata_defaults: false

##
## LOGGING SETTINGS
##
debug: false
logging:
  config: classpath:logback.xml
  level:
    org.n52: DEBUG
    ## Spring
    org.springframework: INFO
    org.springframework.web.servlet.mvc.method.annotation: INFO
    ## Hibernate
    org.hibernate: INFO
    #org.hibernate.type: TRACE
    #org.hibernate.SQL: DEBUG
    ## other
    org.apache: WARN
    org.geotools: WARN
    com.sun.xml: ERROR


##
## REST API SETTINGS
##

## Deployments behind a Proxy need to know the external URL
external:
  url: http://localhost:8081/api/

docs:
  context: docs

##
## IO DEFAULTS
##

## TBD

# gracefully match leap years (P1Y)
request:
  interval:
    restriction: P370D



## Service Configuration
service:
  name: My RESTful Dataset Service
  nodata:
    # NO_DATA values in database which will return null values
    values: -9999.0,99999,NO_DATA
  dcat:
    catalog:
      language: en
      title: Sensor Observation Service Catalog
      description: Catalog of Sensor Observation Service datasets
      homepage: https://52north.org
      publisher: https://52north.org
      license: https://creativecommons.org/licenses/by/4.0/
    persistence:
      path: /tmp/catalog.rdf
      enabled: false

##
## Job Scheduler and Tasks
##

# disables all jobs
job:
  scheduler:
    enabled: false
  task:
    prerendering:
      enabled: true
